# Generated by Django 3.0.7 on 2020-07-03 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacherinfo_user_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherinfo',
            old_name='user_obj',
            new_name='users',
        ),
    ]
