# Generated by Django 3.0.7 on 2020-07-03 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_auto_20200703_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherinfo',
            old_name='users',
            new_name='user',
        ),
    ]
