# Generated by Django 3.0.7 on 2020-07-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20200703_1012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherInfo',
        ),
    ]
