# Generated by Django 3.0.7 on 2020-07-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200704_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetailinfo',
            name='std_session',
            field=models.IntegerField(default=2019),
            preserve_default=False,
        ),
    ]
